#makefile 文件
MAIN_PATH = ..
OBJ_PATH = ${MAIN_PATH}/common/obj
LIB_PATH = ${MAIN_PATH}/lib
BIN_PATH = ${MAIN_PATH}/bin
SRC_PATH = $(MAIN_PATH)/common/src
INC_PATH = $(MAIN_PATH)/common/inc

##编译环境



clean:
	-@rm -f ${OBJ_PATH}/*.o ${LIB_PATH}/libcommon.a 
